### ISSUE TITLE
Quaternion.AngleAxis requires angle in Degrees instead of Radians

### ISSUE THREAD

**Issue by ZephD** [adragonite/math3d#1]
Just a quick question.

What is the design choice for requiring degrees in the constructor? [You simply convert it to radians anyway](https://github.com/adragonite/math3d/blob/master/src/Quaternion.js#L185).

**Comment by adragonite** [comment]
The library was designed to work especially with Unity3D. Hence I tried to stick to its [API](https://docs.unity3d.com/ScriptReference/Quaternion.AngleAxis.html) as much as possible.

**Comment by ZephD** [comment]
A perfectly valid design choice. Thanks.
